Repository Azure/ALZ-Bicep, pull requests merged in 2022-02, with the labels that each got.

#129 Added native VSCode recommendation
  docs/wiki/Contributing.md
Labels: documentation, enhancement

#135 Fix 2 Policy Assignment Scopes
  infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep
Labels: bug, Area: Policy

#136 Fix Missing Parameters from Parameters File for Hub Networking
  infra-as-code/bicep/modules/hubNetworking/README.md
  infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep
  infra-as-code/bicep/modules/hubNetworking/hubNetworking.parameters.example.json
Labels: bug, documentation

#140 Remove .md extension
  docs/wiki/_Sidebar.md
Labels: bug, documentation

#142 Add tag to hub vnet resource
  infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep
Labels: enhancement, Area: Networking

#147 Convert to FabricBot-as-code
  .github/fabricbot.json
Labels: enhancement, hygiene

#148 Update Linter Rules From Latest Bicep Release & Fix Hub Networking Conditionals
  docs/wiki/Contributing.md
  infra-as-code/bicep/CRML/containerRegistry/bicepconfig.json
  infra-as-code/bicep/CRML/customerUsageAttribution/bicepconfig.json
  infra-as-code/bicep/CRML/subscriptionAlias/bicepconfig.json
  infra-as-code/bicep/modules/customRoleDefinitions/bicepconfig.json
  infra-as-code/bicep/modules/customRoleDefinitions/customRoleDefinitions.bicep
  infra-as-code/bicep/modules/hubNetworking/README.md
  infra-as-code/bicep/modules/hubNetworking/bicepconfig.json
  infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep
  infra-as-code/bicep/modules/hubNetworking/hubNetworking.parameters.example.json
  infra-as-code/bicep/modules/logging/bicepconfig.json
  infra-as-code/bicep/modules/logging/logging.bicep
  infra-as-code/bicep/modules/managementGroups/bicepconfig.json
  infra-as-code/bicep/modules/managementGroups/managementGroups.bicep
  infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep
  infra-as-code/bicep/modules/policy/assignments/alzDefaults/bicepconfig.json
  infra-as-code/bicep/modules/policy/assignments/bicepconfig.json
  infra-as-code/bicep/modules/policy/assignments/policyAssignmentManagementGroup.bicep
  infra-as-code/bicep/modules/policy/definitions/bicepconfig.json
  infra-as-code/bicep/modules/policy/definitions/custom-policy-definitions.bicep
  infra-as-code/bicep/modules/publicIp/README.md
  infra-as-code/bicep/modules/publicIp/bicepconfig.json
  infra-as-code/bicep/modules/publicIp/publicIp.bicep
  infra-as-code/bicep/modules/resourceGroup/bicepconfig.json
  infra-as-code/bicep/modules/roleAssignments/bicepconfig.json
  infra-as-code/bicep/modules/roleAssignments/roleAssignmentManagementGroup.bicep
  infra-as-code/bicep/modules/spokeNetworking/README.md
  infra-as-code/bicep/modules/spokeNetworking/bicepconfig.json
  infra-as-code/bicep/modules/spokeNetworking/spokeNetworking.bicep
  infra-as-code/bicep/modules/spokeNetworking/spokeNetworking.parameters.example.json
  infra-as-code/bicep/modules/subscriptionPlacement/bicepconfig.json
  infra-as-code/bicep/modules/subscriptionPlacement/subscriptionPlacement.bicep
  infra-as-code/bicep/modules/unstable/orchestration/hubSpoke/bicepconfig.json
  infra-as-code/bicep/modules/virtualNetworkPeer/bicepconfig.json
  infra-as-code/bicep/modules/virtualNetworkPeer/virtualNetworkPeer.bicep
Labels: bug, enhancement, Needs: Triage :mag:, Area: Networking, hygiene

#149 Update unit tests for bicep and close PR job
  .github/workflows/bicep-build-to-validate.yml
  .github/workflows/cleanup-on-close-pr.yml
Labels: hygiene

#143 Include managementGroup().name as part of role assignment GUID to avoid possible duplicates.
  infra-as-code/bicep/modules/roleAssignments/README.md
  infra-as-code/bicep/modules/roleAssignments/roleAssignmentManagementGroup.bicep
Labels: enhancement, Area: RBAC

#150 Add Markdown Link Checker
  .github/actions-config/mlc_config.json
  .github/workflows/code-review.yml
  docs/wiki/CustomerUsage.md
  docs/wiki/_Sidebar.md
  infra-as-code/bicep/CRML/customerUsageAttribution/README.md
Labels: enhancement, hygiene

#151 Update parLogAnalyticsWorkspaceResourceID with empty string default value
  infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep
Labels: hygiene

#155 Add Note About Assignments to Definitions Module
  infra-as-code/bicep/modules/policy/definitions/README.md
Labels: documentation, enhancement, Needs: Triage :mag:, Area: Policy

#156 Minor typo fixes
  infra-as-code/bicep/modules/roleAssignments/README.md
Labels: bug, documentation

#167 Add note about `#disable-next-line` to each usage and FAQ
  docs/wiki/FAQ.md
  infra-as-code/bicep/modules/customRoleDefinitions/customRoleDefinitions.bicep
  infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep
  infra-as-code/bicep/modules/logging/logging.bicep
  infra-as-code/bicep/modules/managementGroups/managementGroups.bicep
  infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep
  infra-as-code/bicep/modules/policy/assignments/policyAssignmentManagementGroup.bicep
  infra-as-code/bicep/modules/policy/definitions/custom-policy-definitions.bicep
  infra-as-code/bicep/modules/publicIp/publicIp.bicep
  infra-as-code/bicep/modules/roleAssignments/roleAssignmentManagementGroup.bicep
  infra-as-code/bicep/modules/subscriptionPlacement/subscriptionPlacement.bicep
  infra-as-code/bicep/modules/virtualNetworkPeer/virtualNetworkPeer.bicep
Labels: documentation, enhancement

#162 Add sample GitHub Action and Azure Pipeline to wiki
  README.md
  docs/wiki/Home.md
  docs/wiki/PipelinesADO.md
  docs/wiki/PipelinesGitHub.md
  docs/wiki/PipelinesOverview.md
  docs/wiki/_Sidebar.md
Labels: documentation, enhancement
