Repository Azure/ALZ-Bicep, pull requests merged in 2022-09, with the labels that each got.

#313 Add PSRule To ALZ Bicep Testing
  .github/workflows/bicep-build-to-validate.yml
  .ps-rule/FalsePositiveNsgBastion.Rule.yaml
  .ps-rule/Minimum.Rule.yaml
  .ps-rule/UnsupportedPipBastion.Rule.yaml
  .ps-rule/en/ALZ.MinimumSample.md
  .vscode/bicep.code-snippets
  .vscode/extensions.json
  .vscode/tasks.json
  docs/wiki/Contributing.md
  infra-as-code/bicep/modules/hubNetworking/samples/baseline.sample.bicep
  infra-as-code/bicep/modules/hubNetworking/samples/minimum.sample.bicep
  infra-as-code/bicep/modules/publicIp/samples/baseline.sample.bicep
  infra-as-code/bicep/modules/publicIp/samples/minimum.sample.bicep
  ps-rule.yaml
Labels: Needs: Triage :mag:

#315 Enable GitHub to ADO WIT Sync
  .github/actions-config/gh-ado-sync-config.json
  .github/workflows/gh-ado-sync.yml
Labels: hygiene

#318 chore: bicepconfig.json linter update
  .github/workflows/bicep-build-to-validate.yml
  docs/wiki/Contributing.md
  infra-as-code/bicep/CRML/containerRegistry/bicepconfig.json
  infra-as-code/bicep/CRML/containerRegistry/containerRegistry.bicep
  infra-as-code/bicep/CRML/customerUsageAttribution/bicepconfig.json
  infra-as-code/bicep/CRML/subscriptionAlias/bicepconfig.json
  infra-as-code/bicep/modules/customRoleDefinitions/bicepconfig.json
  infra-as-code/bicep/modules/customRoleDefinitions/definitions/cafApplicationOwnerRole.bicep
  infra-as-code/bicep/modules/customRoleDefinitions/definitions/cafNetworkManagementRole.bicep
  infra-as-code/bicep/modules/customRoleDefinitions/definitions/cafSecurityOperationsRole.bicep
  infra-as-code/bicep/modules/customRoleDefinitions/definitions/cafSubscriptionOwnerRole.bicep
  infra-as-code/bicep/modules/customRoleDefinitions/definitions/china/mc-cafNetworkManagementRole.bicep
  infra-as-code/bicep/modules/customRoleDefinitions/definitions/china/mc-cafSecurityOperationsRole.bicep
  infra-as-code/bicep/modules/hubNetworking/bicepconfig.json
  infra-as-code/bicep/modules/logging/bicepconfig.json
  infra-as-code/bicep/modules/managementGroups/bicepconfig.json
  infra-as-code/bicep/modules/managementGroups/managementGroups.bicep
  infra-as-code/bicep/modules/policy/assignments/alzDefaults/bicepconfig.json
  infra-as-code/bicep/modules/policy/assignments/bicepconfig.json
  infra-as-code/bicep/modules/policy/assignments/policyAssignmentManagementGroup.bicep
  infra-as-code/bicep/modules/policy/definitions/bicepconfig.json
  infra-as-code/bicep/modules/policy/definitions/customPolicyDefinitions.bicep
  infra-as-code/bicep/modules/policy/definitions/mc-customPolicyDefinitions.bicep
  infra-as-code/bicep/modules/privateDnsZones/bicepconfig.json
  infra-as-code/bicep/modules/publicIp/bicepconfig.json
  infra-as-code/bicep/modules/resourceGroup/bicepconfig.json
  infra-as-code/bicep/modules/roleAssignments/bicepconfig.json
  infra-as-code/bicep/modules/roleAssignments/roleAssignmentManagementGroup.bicep
  infra-as-code/bicep/modules/roleAssignments/roleAssignmentSubscription.bicep
  infra-as-code/bicep/modules/spokeNetworking/bicepconfig.json
  infra-as-code/bicep/modules/subscriptionPlacement/bicepconfig.json
  infra-as-code/bicep/modules/unstable/orchestration/hubSpoke/bicepconfig.json
  infra-as-code/bicep/modules/vnetPeering/bicepconfig.json
  infra-as-code/bicep/modules/vnetPeeringVwan/bicepconfig.json
  infra-as-code/bicep/modules/vwanConnectivity/bicepconfig.json
  infra-as-code/bicep/orchestration/hubPeeredSpoke/bicepconfig.json
  infra-as-code/bicep/orchestration/subPlacementAll/bicepconfig.json
Labels: hygiene, Area: Non-Resource Specific, do not merge

#322 doc: Added subnet disclaimer
  infra-as-code/bicep/modules/spokeNetworking/README.md
Labels: Needs: Triage :mag:

#324 capture definitionReferenceId that starts with number.
  .github/scripts/Invoke-PolicyToBicep.ps1
Labels: bug, enhancement, Area: Policy
