Repository Azure/ALZ-Bicep, pull requests merged in 2022-04, with the labels that each got.

#198 Upped aliases API version to non-preview
  infra-as-code/bicep/CRML/subscriptionAlias/README.md
  infra-as-code/bicep/CRML/subscriptionAlias/parameters/subscriptionAlias.parameters.example.json
  infra-as-code/bicep/CRML/subscriptionAlias/parameters/subscriptionAlias.parameters.minimum.example.json
  infra-as-code/bicep/CRML/subscriptionAlias/subscriptionAlias.bicep
  tests/pipelines/bicep-build-to-validate.yml
Labels: enhancement, Area: Non-Resource Specific, external community contribution

#200 Added Resource Group output
  infra-as-code/bicep/modules/resourceGroup/README.md
  infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep
Labels: enhancement, Needs: Triage :mag:, Area: Non-Resource Specific

#165 Implementing the option for Private DNS Zones in a separate Resource Group
  infra-as-code/bicep/modules/hubNetworking/README.md
  infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep
  infra-as-code/bicep/modules/hubNetworking/hubNetworking.parameters.example.json
  infra-as-code/bicep/modules/hubNetworking/mc-hubNetworking.parameters.example.json
  infra-as-code/bicep/modules/hubNetworking/media/hubNetworkingBicepVisualizer.png
  infra-as-code/bicep/modules/privateDnsZones/README.md
  infra-as-code/bicep/modules/privateDnsZones/bicepconfig.json
  infra-as-code/bicep/modules/privateDnsZones/mc-privateDnsZones.parameters.example.json
  infra-as-code/bicep/modules/privateDnsZones/media/privateDnsZonesBicepVisualizer.png
  infra-as-code/bicep/modules/privateDnsZones/media/privateDnsZonesExampleDeploymentOutput.png
  infra-as-code/bicep/modules/privateDnsZones/privateDnsZones.bicep
  infra-as-code/bicep/modules/privateDnsZones/privateDnsZones.parameters.example.json
Labels: enhancement, Area: Networking, external community contribution

#208 Add tracking PID to wiki docs for new `privateDnsZones` module
  docs/wiki/CustomerUsage.md
Labels: documentation, Area: Networking, hygiene, Area: Non-Resource Specific

#201 E2E test for vwan network connection
  .github/workflows/code-review.yml
  tests/pipelines/bicep-build-to-validate.yml
Labels: hygiene

#210 Update PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hygiene

#207 Initial PSRule without parameter files #206
  .github/workflows/bicep-build-to-validate.yml
  .vscode/extensions.json
  .vscode/tasks.json
  docs/wiki/Contributing.md
  ps-rule.yaml
Labels: hygiene, Area: Non-Resource Specific

#214 vnetPeering Module Hygiene - Backlog Item 106634
  infra-as-code/bicep/modules/vnetPeering/README.md
  infra-as-code/bicep/modules/vnetPeering/bicepconfig.json
  infra-as-code/bicep/modules/vnetPeering/media/bicepVisualizer.png
  infra-as-code/bicep/modules/vnetPeering/vnetPeering.bicep
Labels: Area: Networking

#215 Add vnetpeering to E2E testing
  .vscode/tours/E2Etesttour.tour
  tests/pipelines/bicep-build-to-validate.yml
Labels: Needs: Triage :mag:, do not merge

#218 Remove comment blocks from module - Backlog Item 83064
  docs/wiki/Contributing.md
  infra-as-code/bicep/modules/customRoleDefinitions/customRoleDefinitions.bicep
  infra-as-code/bicep/modules/customRoleDefinitions/mc-customRoleDefinitions.bicep
  infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep
  infra-as-code/bicep/modules/logging/logging.bicep
  infra-as-code/bicep/modules/managementGroups/managementGroups.bicep
  infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep
  infra-as-code/bicep/modules/policy/assignments/policyAssignmentManagementGroup.bicep
  infra-as-code/bicep/modules/policy/definitions/custom-policy-definitions.bicep
  infra-as-code/bicep/modules/policy/definitions/mc-custom-policy-definitions.bicep
  infra-as-code/bicep/modules/privateDnsZones/privateDnsZones.bicep
  infra-as-code/bicep/modules/publicIp/publicIp.bicep
  infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep
  infra-as-code/bicep/modules/roleAssignments/roleAssignmentManagementGroup.bicep
  infra-as-code/bicep/modules/roleAssignments/roleAssignmentManagementGroupMany.bicep
  infra-as-code/bicep/modules/roleAssignments/roleAssignmentSubscription.bicep
  infra-as-code/bicep/modules/roleAssignments/roleAssignmentSubscriptionMany.bicep
  infra-as-code/bicep/modules/spokeNetworking/spokeNetworking.bicep
  infra-as-code/bicep/modules/subscriptionPlacement/subscriptionPlacement.bicep
  infra-as-code/bicep/modules/unstable/orchestration/hubSpoke/orch-hubSpoke.bicep
  infra-as-code/bicep/modules/vnetPeeringVwan/hubVirtualNetworkConnection.bicep
  infra-as-code/bicep/modules/vnetPeeringVwan/vnetPeeringVwan.bicep
  infra-as-code/bicep/modules/vwanConnectivity/vwanConnectivity.bicep
Labels: enhancement, hygiene, Area: Non-Resource Specific

#221 remove deprecated extension from Contributing guide - Backlog Item 110091
  docs/wiki/Contributing.md
Labels: Needs: Triage :mag:

#220 Update vnetPeering documentation and samples
  .vscode/tours/E2Etesttour.tour
  infra-as-code/bicep/modules/vnetPeering/README.md
  infra-as-code/bicep/modules/vnetPeering/media/vnetPeeringExampleDeploymentOutput.png
  infra-as-code/bicep/modules/vnetPeering/vnetPeering.parameters.example.json
  tests/pipelines/bicep-build-to-validate.yml
Labels: Area: Networking, hygiene
