Repository Azure/ALZ-Bicep, pull requests merged in 2022-10, with the labels that each got.

#325 Add `.editorconfig` support
  .editorconfig
  .gitattributes
  .github/workflows/code-review.yml
  .vscode/bicep.code-snippets
  .vscode/extensions.json
  .vscode/tasks.json
  docs/wiki/Contributing.md
Labels: hygiene

#306 Add AZ Support for VPN & ER GW PIPs
  infra-as-code/bicep/modules/hubNetworking/README.md
  infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep
  infra-as-code/bicep/modules/hubNetworking/parameters/hubNetworking.parameters.all.json
  infra-as-code/bicep/modules/hubNetworking/parameters/hubNetworking.parameters.min.json
  infra-as-code/bicep/modules/hubNetworking/parameters/mc-hubNetworking.parameters.all.json
  infra-as-code/bicep/modules/hubNetworking/parameters/mc-hubNetworking.parameters.min.json
  infra-as-code/bicep/modules/hubNetworking/samples/baseline.sample.bicep
  infra-as-code/bicep/modules/hubNetworking/samples/minimum.sample.bicep
Labels: Area: Networking

#321 Management Group Diagnostic Settings Enablement - New Module
  .vscode/tours/azurechinacloud-base-validation-pipeline.tour
  .vscode/tours/azurecloud-base-validation-pipeline.tour
  docs/wiki/CustomerUsage.md
  docs/wiki/DeploymentFlow.md
  docs/wiki/media/high-level-deployment-flow.png
  infra-as-code/bicep/modules/mgDiagSettings/README.md
  infra-as-code/bicep/modules/mgDiagSettings/bicepconfig.json
  infra-as-code/bicep/modules/mgDiagSettings/media/bicepVisualizer.png
  infra-as-code/bicep/modules/mgDiagSettings/mgDiagSettings.bicep
  infra-as-code/bicep/modules/mgDiagSettings/parameters/mgDiagSettings.parameters.all.json
  infra-as-code/bicep/modules/mgDiagSettings/parameters/mgDiagSettings.parameters.min.json
  infra-as-code/bicep/orchestration/mgDiagSettingsAll/README.md
  infra-as-code/bicep/orchestration/mgDiagSettingsAll/bicepconfig.json
  infra-as-code/bicep/orchestration/mgDiagSettingsAll/media/bicepVisualizer.png
  infra-as-code/bicep/orchestration/mgDiagSettingsAll/mgDiagSettingsAll.bicep
  infra-as-code/bicep/orchestration/mgDiagSettingsAll/parameters/mgDiagSettingsAll.parameters.all.json
  infra-as-code/bicep/orchestration/mgDiagSettingsAll/parameters/mgDiagSettingsAll.parameters.min.json
  tests/pipelines/base-unit-validate.yml
  tests/pipelines/bicep-build-to-validate.yml
  tests/pipelines/mc-base-unit-validate.yml
Labels: enhancement, Area: Management Groups, Area: Logging & Automation, Area: Orchestration Modules

#335 Fix #334 - fix deployment errors related to Network.DNS.Proxy
  infra-as-code/bicep/modules/vwanConnectivity/vwanConnectivity.bicep
Labels: bug, Needs: Triage :mag:, Area: Networking, do not merge

#333 Bump PSRule.Azure Baseline to Azure.GA_2022_09
  .github/workflows/bicep-build-to-validate.yml
Labels: hygiene

#345 Azure Commercial Cloud - Update Policy Library - ADO #22240
  .github/scripts/EnterpriseScaleLibraryTools/EnterpriseScaleLibraryTools.psd1
  .github/scripts/EnterpriseScaleLibraryTools/EnterpriseScaleLibraryTools.psm1
  .github/scripts/EnterpriseScaleLibraryTools/ProviderApiVersions.zip
  .github/scripts/Invoke-LibraryUpdate.ps1
  .github/workflows/update-policy.yml
Labels: Area: Policy

#343 Update json file loading to use loadJsonContent
  .github/scripts/Get-AlzBicepResourceTypes.ps1
  .github/scripts/Invoke-PolicyToBicep-China.ps1
  .github/scripts/Invoke-PolicyToBicep.ps1
  .github/workflows/bicep-build-to-validate.yml
  README.md
  infra-as-code/bicep/modules/policy/assignments/README.md
  infra-as-code/bicep/modules/policy/assignments/lib/README.md
  infra-as-code/bicep/modules/policy/assignments/policyAssignmentManagementGroup.bicep
  infra-as-code/bicep/modules/policy/definitions/customPolicyDefinitions.bicep
  infra-as-code/bicep/modules/policy/definitions/mc-customPolicyDefinitions.bicep
  infra-as-code/bicep/modules/unstable/orchestration/hubSpoke/README.md
  infra-as-code/bicep/modules/unstable/orchestration/hubSpoke/bicepconfig.json
  infra-as-code/bicep/modules/unstable/orchestration/hubSpoke/orchHubSpoke.bicep
  infra-as-code/bicep/modules/unstable/orchestration/hubSpoke/parameters/orchHubSpoke.parameters.all.json
Labels: Area: Policy

#349 Prep for release of v0.10.6
  version.json
Labels: hygiene

#350 Azure Commercial Cloud - Policy Update Issue in Workflow
  .github/scripts/Invoke-LibraryUpdate.ps1
  .github/scripts/Invoke-PolicyToBicep.ps1
  .github/workflows/update-policy.yml
Labels: Needs: Triage :mag:

#351 Azure China Cloud - Policy Refactoring
  .github/scripts/Invoke-LibraryUpdate-China.ps1
  .github/scripts/Invoke-PolicyToBicep-China.ps1
  .github/workflows/update-policy-china.yml
Labels: Area: Policy

#353 Fix bicep example for parLandingZoneMgChildren
  infra-as-code/bicep/orchestration/mgDiagSettingsAll/README.md
Labels: Needs: Triage :mag:

#331 Updated markdowns to correspond with the Bicep files
  infra-as-code/bicep/modules/customRoleDefinitions/README.md
  infra-as-code/bicep/modules/customRoleDefinitions/customRoleDefinitions.bicep
  infra-as-code/bicep/modules/customRoleDefinitions/mc-customRoleDefinitions.bicep
  infra-as-code/bicep/modules/hubNetworking/README.md
  infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep
  infra-as-code/bicep/modules/logging/README.md
  infra-as-code/bicep/modules/logging/logging.bicep
  infra-as-code/bicep/modules/managementGroups/README.md
  infra-as-code/bicep/modules/managementGroups/managementGroups.bicep
  infra-as-code/bicep/modules/privateDnsZones/README.md
  infra-as-code/bicep/modules/privateDnsZones/privateDnsZones.bicep
  infra-as-code/bicep/modules/publicIp/README.md
  infra-as-code/bicep/modules/publicIp/publicIp.bicep
  infra-as-code/bicep/modules/resourceGroup/README.md
  infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep
  infra-as-code/bicep/modules/roleAssignments/README.md
  infra-as-code/bicep/modules/roleAssignments/roleAssignmentManagementGroup.bicep
  infra-as-code/bicep/modules/roleAssignments/roleAssignmentManagementGroupMany.bicep
  infra-as-code/bicep/modules/roleAssignments/roleAssignmentSubscription.bicep
  infra-as-code/bicep/modules/roleAssignments/roleAssignmentSubscriptionMany.bicep
  infra-as-code/bicep/modules/spokeNetworking/README.md
  infra-as-code/bicep/modules/spokeNetworking/spokeNetworking.bicep
  infra-as-code/bicep/modules/subscriptionPlacement/README.md
  infra-as-code/bicep/modules/subscriptionPlacement/subscriptionPlacement.bicep
  infra-as-code/bicep/modules/vnetPeering/README.md
  infra-as-code/bicep/modules/vnetPeering/vnetPeering.bicep
  infra-as-code/bicep/modules/vnetPeeringVwan/README.md
  infra-as-code/bicep/modules/vnetPeeringVwan/hubVirtualNetworkConnection.bicep
  infra-as-code/bicep/modules/vnetPeeringVwan/vnetPeeringVwan.bicep
  infra-as-code/bicep/orchestration/hubPeeredSpoke/README.md
  infra-as-code/bicep/orchestration/hubPeeredSpoke/hubPeeredSpoke.bicep
  infra-as-code/bicep/orchestration/mgDiagSettingsAll/README.md
  infra-as-code/bicep/orchestration/mgDiagSettingsAll/mgDiagSettingsAll.bicep
  infra-as-code/bicep/orchestration/subPlacementAll/README.md
  infra-as-code/bicep/orchestration/subPlacementAll/subPlacementAll.bicep
Labels: documentation, external community contribution
