Repository Azure/ALZ-Bicep, pull requests merged in 2022-03, with the labels that each got.

#168 Update unit tests for vWan
  tests/pipelines/bicep-build-to-validate.yml
Labels: Area: Networking, hygiene

#169 Vwanunittests
  tests/pipelines/bicep-build-to-validate.yml
Labels: Area: Networking, hygiene

#171 Tagging update
  infra-as-code/bicep/modules/logging/README.md
  infra-as-code/bicep/modules/logging/logging.bicep
  infra-as-code/bicep/modules/logging/logging.parameters.example.json
  infra-as-code/bicep/modules/logging/mc-logging.parameters.example.json
  infra-as-code/bicep/modules/resourceGroup/README.md
  infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep
Labels: Area: Logging & Automation, Area: Non-Resource Specific

#172 Fix remaining conditions for vWan deployment
  .github/scripts/Wipe-AlzTenant.ps1
  .github/scripts/Wipe-ESLZAzTenant.ps1
  tests/pipelines/bicep-build-to-validate.yml
Labels: hygiene

#152 Enabled Virtual WAN scenario in a new vwanConnectivity module
  docs/wiki/CustomerUsage.md
  docs/wiki/DeploymentFlow.md
  docs/wiki/DeploymentFlowHS.md
  docs/wiki/DeploymentFlowVWAN.md
  docs/wiki/_Sidebar.md
  docs/wiki/media/high-level-deployment-flow.png
  infra-as-code/bicep/modules/vwanConnectivity/README.md
  infra-as-code/bicep/modules/vwanConnectivity/bicepconfig.json
  infra-as-code/bicep/modules/vwanConnectivity/media/mc-vwanConnectivityExampleDeploymentOutput.png
  infra-as-code/bicep/modules/vwanConnectivity/media/mc-vwanExampleDeploymentOutput.png
  infra-as-code/bicep/modules/vwanConnectivity/media/vwanConnectivityBicepVisualizer.png
  infra-as-code/bicep/modules/vwanConnectivity/media/vwanConnectivityExampleDeploymentOutput.png
  infra-as-code/bicep/modules/vwanConnectivity/media/vwanExampleDeploymentOutput.png
  infra-as-code/bicep/modules/vwanConnectivity/vwanConnectivity.bicep
  infra-as-code/bicep/modules/vwanConnectivity/vwanConnectivity.parameters.example.json
Labels: enhancement, Area: Networking

#177 Add Missing Databricks Default Policy Assignments to Corp MG to Match ALZ Accelerator Experience
  infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep
  infra-as-code/bicep/modules/policy/assignments/lib/policy_assignments/_policyAssignmentsBicepInput.txt
  infra-as-code/bicep/modules/policy/assignments/lib/policy_assignments/policy_assignment_es_deny_databricks_public_ip.tmpl.json
  infra-as-code/bicep/modules/policy/assignments/lib/policy_assignments/policy_assignment_es_deny_databricks_sku.tmpl.json
  infra-as-code/bicep/modules/policy/assignments/lib/policy_assignments/policy_assignment_es_deny_databricks_vnet.tmpl.json
Labels: bug, enhancement, Needs: Triage :mag:, Area: Policy

#175 Update parameter order for hubnetworking
  infra-as-code/bicep/modules/hubNetworking/README.md
  infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep
  infra-as-code/bicep/modules/hubNetworking/hubNetworking.parameters.example.json
  infra-as-code/bicep/modules/hubNetworking/mc-hubNetworking.parameters.example.json
Labels: enhancement, Area: Networking

#182 Add condition to `Enable-DDoS-VNET` policy assignments in `alzDefaultPolicyAssignments`
  infra-as-code/bicep/modules/policy/assignments/alzDefaults/README.md
  infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep
Labels: bug, enhancement, Area: Policy

#184 Add spoke vnet tagging
  infra-as-code/bicep/modules/spokeNetworking/spokeNetworking.bicep
  infra-as-code/bicep/modules/spokeNetworking/spokeNetworking.parameters.example.json
Labels: Area: Networking, hygiene, Area: Non-Resource Specific

#188 useRemoteGatewaysAdded property added to virtualNetworkPeer module
  infra-as-code/bicep/modules/virtualNetworkPeer/README.md
  infra-as-code/bicep/modules/virtualNetworkPeer/virtualNetworkPeer.bicep
Labels: enhancement, Area: Networking

#190 Add type to custom role definitions
  infra-as-code/bicep/modules/customRoleDefinitions/definitions/caf-application-owner-role.bicep
  infra-as-code/bicep/modules/customRoleDefinitions/definitions/caf-network-management-role.bicep
  infra-as-code/bicep/modules/customRoleDefinitions/definitions/caf-security-operations-role.bicep
  infra-as-code/bicep/modules/customRoleDefinitions/definitions/caf-subscription-owner-role.bicep
Labels: enhancement, Needs: Triage :mag:, Area: RBAC

#191 Add Consumer Guide
  README.md
  docs/wiki/ACRDeployment.md
  docs/wiki/ConsumerGuide.md
  docs/wiki/DeploymentFlow.md
  docs/wiki/Home.md
  docs/wiki/_Sidebar.md
Labels: documentation, enhancement, Needs: Triage :mag:

#174 Standardize on parLocation for specifying Azure regions.
  docs/wiki/Contributing.md
  docs/wiki/FAQ.md
  docs/wiki/PipelinesADO.md
  docs/wiki/PipelinesGitHub.md
  infra-as-code/bicep/modules/hubNetworking/README.md
  infra-as-code/bicep/modules/logging/README.md
  infra-as-code/bicep/modules/logging/logging.bicep
  infra-as-code/bicep/modules/logging/logging.parameters.example.json
  infra-as-code/bicep/modules/logging/mc-logging.parameters.example.json
  infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep
  infra-as-code/bicep/modules/spokeNetworking/README.md
  infra-as-code/bicep/modules/spokeNetworking/spokeNetworking.bicep
  infra-as-code/bicep/modules/spokeNetworking/spokeNetworking.parameters.example.json
  infra-as-code/bicep/modules/unstable/orchestration/hubSpoke/orch-hubSpoke.bicep
Labels: documentation, enhancement, hygiene, Area: Non-Resource Specific

#185 Spoke Vnet peering with Vwan virtual hub
  docs/wiki/CustomerUsage.md
  docs/wiki/DeploymentFlowVWAN.md
  infra-as-code/bicep/modules/vnetPeeringVwan/README.md
  infra-as-code/bicep/modules/vnetPeeringVwan/bicepconfig.json
  infra-as-code/bicep/modules/vnetPeeringVwan/hubVirtualNetworkConnection.bicep
  infra-as-code/bicep/modules/vnetPeeringVwan/media/vnetPeeringVwanBicepVisualizer.png
  infra-as-code/bicep/modules/vnetPeeringVwan/media/vnetPeeringVwanExampleDeploymentOutput.png
  infra-as-code/bicep/modules/vnetPeeringVwan/vnetPeeringVwan.bicep
  infra-as-code/bicep/modules/vnetPeeringVwan/vnetPeeringVwan.parameters.example.json
Labels: enhancement, Area: Networking

#183 Swap individual policy assignments to `alzDefaultPolicyAssignments` module in E2E tests
  .github/scripts/Set-AlzDefaultPolicyAssignment.ps1
  tests/pipelines/bicep-build-to-validate.yml
Labels: enhancement, Area: Policy, hygiene
