Repository Azure/ALZ-Bicep, pull requests merged in 2023-03, with the labels that each got.

#474 Remove unrequired parameters from `mgDiagSettings` - Fix #473
  infra-as-code/bicep/modules/mgDiagSettings/parameters/mgDiagSettings.parameters.all.json
  infra-as-code/bicep/modules/mgDiagSettings/parameters/mgDiagSettings.parameters.min.json
Labels: bug, Area: Management Groups, Area: Logging & Automation

#466 26740 - Feature - Generated Parameter Markdowns for Orchestration
  .github/workflows/psdocs-mdtogit.yml
  infra-as-code/bicep/CRML/containerRegistry/README.md
  infra-as-code/bicep/CRML/containerRegistry/generateddocs/containerRegistry.bicep.md
  infra-as-code/bicep/CRML/customerUsageAttribution/README.md
  infra-as-code/bicep/CRML/customerUsageAttribution/generateddocs/cuaIdManagementGroup.bicep.md
  infra-as-code/bicep/CRML/customerUsageAttribution/generateddocs/cuaIdResourceGroup.bicep.md
  infra-as-code/bicep/CRML/customerUsageAttribution/generateddocs/cuaIdSubscription.bicep.md
  infra-as-code/bicep/CRML/customerUsageAttribution/generateddocs/cuaIdTenant.bicep.md
  infra-as-code/bicep/CRML/subscriptionAlias/README.md
  infra-as-code/bicep/CRML/subscriptionAlias/generateddocs/subscriptionAlias.bicep.md
  infra-as-code/bicep/orchestration/hubPeeredSpoke/README.md
  infra-as-code/bicep/orchestration/hubPeeredSpoke/generateddocs/hubPeeredSpoke.bicep.md
  infra-as-code/bicep/orchestration/mgDiagSettingsAll/README.md
  infra-as-code/bicep/orchestration/mgDiagSettingsAll/generateddocs/mgDiagSettingsAll.bicep.md
  infra-as-code/bicep/orchestration/subPlacementAll/README.md
  infra-as-code/bicep/orchestration/subPlacementAll/generateddocs/subPlacementAll.bicep.md
Labels: documentation

#482 Deploy-VM-Backup optional parameters for exclusion tag
  infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep
  infra-as-code/bicep/modules/policy/assignments/alzDefaults/generateddocs/alzDefaultPolicyAssignments.bicep.md
  infra-as-code/bicep/modules/policy/assignments/alzDefaults/parameters/alzDefaultPolicyAssignments.parameters.all.json
Labels: enhancement, Area: Policy, external community contribution

#483 26294 - Feature - Accelerator Pipeline Adjustments
  accelerator/.github/workflows/alz-bicep-2.yml
  accelerator/pipeline-scripts/Deploy-ALZPolicyAssignments.ps1
  accelerator/pipeline-scripts/Deploy-ALZSubscriptionPlacement.ps1
  infra-as-code/bicep/CRML/containerRegistry/parameters/containerRegistry.parameters.all.json
  infra-as-code/bicep/CRML/subscriptionAlias/parameters/subscriptionAlias.parameters.all.json
  infra-as-code/bicep/modules/hubNetworking/parameters/hubNetworking.parameters.all.json
  infra-as-code/bicep/modules/hubNetworking/parameters/mc-hubNetworking.parameters.all.json
  infra-as-code/bicep/modules/logging/parameters/logging.parameters.all.json
  infra-as-code/bicep/modules/logging/parameters/mc-logging.parameters.all.json
  infra-as-code/bicep/modules/privateDnsZones/parameters/privateDnsZones.parameters.all.json
  infra-as-code/bicep/modules/publicIp/parameters/publicIp.parameters.all.json
  infra-as-code/bicep/modules/resourceGroup/parameters/resourceGroup.parameters.all.json
  infra-as-code/bicep/modules/spokeNetworking/parameters/spokeNetworking.parameters.all.json
  infra-as-code/bicep/modules/vwanConnectivity/parameters/mc-vwanConnectivity.parameters.all.json
  infra-as-code/bicep/modules/vwanConnectivity/parameters/vwanConnectivity.parameters.all.json
  infra-as-code/bicep/orchestration/hubPeeredSpoke/parameters/hubPeeredSpoke.parameters.all.json
  infra-as-code/bicep/orchestration/hubPeeredSpoke/parameters/hubPeeredSpoke.vwan.parameters.all.json
Labels: Needs: Triage :mag:
