Repository Azure/ALZ-Bicep, pull requests merged in 2023-08, with the labels that each got.

#597 fix: Description of parPlatformMgAlzDefaultsEnable
  infra-as-code/bicep/orchestration/mgDiagSettingsAll/generateddocs/mgDiagSettingsAll.bicep.md
  infra-as-code/bicep/orchestration/mgDiagSettingsAll/mgDiagSettingsAll.bicep
Labels: bug, documentation, Area: Management Groups

#607 Add Bastion native client support
  infra-as-code/bicep/modules/hubNetworking/generateddocs/hubNetworking.bicep.md
  infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep
Labels: enhancement, Area: Networking, external community contribution

#612 Add VWAN Features: Routing Intent, VHC Naming, Enable Internet Security
  infra-as-code/bicep/modules/vnetPeeringVwan/generateddocs/hubVirtualNetworkConnection.bicep.md
  infra-as-code/bicep/modules/vnetPeeringVwan/generateddocs/vnetPeeringVwan.bicep.md
  infra-as-code/bicep/modules/vnetPeeringVwan/hubVirtualNetworkConnection.bicep
  infra-as-code/bicep/modules/vnetPeeringVwan/parameters/vnetPeeringVwan.parameters.all.json
  infra-as-code/bicep/modules/vnetPeeringVwan/vnetPeeringVwan.bicep
  infra-as-code/bicep/modules/vwanConnectivity/generateddocs/vwanConnectivity.bicep.md
  infra-as-code/bicep/modules/vwanConnectivity/parameters/mc-vwanConnectivity.parameters.all.json
  infra-as-code/bicep/modules/vwanConnectivity/parameters/mc-vwanConnectivity.parameters.min.json
  infra-as-code/bicep/modules/vwanConnectivity/parameters/vwanConnectivity.parameters.all.json
  infra-as-code/bicep/modules/vwanConnectivity/parameters/vwanConnectivity.parameters.min.json
  infra-as-code/bicep/modules/vwanConnectivity/samples/baseline.sample.bicep
  infra-as-code/bicep/modules/vwanConnectivity/vwanConnectivity.bicep
  infra-as-code/bicep/orchestration/hubPeeredSpoke/generateddocs/hubPeeredSpoke.bicep.md
  infra-as-code/bicep/orchestration/hubPeeredSpoke/hubPeeredSpoke.bicep
  infra-as-code/bicep/orchestration/hubPeeredSpoke/parameters/hubPeeredSpoke.parameters.all.json
  infra-as-code/bicep/orchestration/hubPeeredSpoke/parameters/hubPeeredSpoke.vwan.parameters.all.json
Labels: enhancement, Area: Networking

#614 Updates to Accelerator Documentation
  docs/wiki/Accelerator.md
Labels: Needs: Attention :wave:
