Repository Azure/ALZ-Bicep, pull requests merged in 2024-06, with the labels that each got.

#787 [Bug - vwanConnectivity] outAzFwPrivateIps output index error
  infra-as-code/bicep/modules/vwanConnectivity/vwanConnectivity.bicep
Labels: bug, Area: Networking :globe_with_meridians:

#788 chore: add release action to generate artifacts for accelerator
  .github/workflows/release.yml
Labels: enhancement

#789 Add OpenSSF Scorecard
  .github/workflows/scorecard.yml
  README.md
Labels: hygiene

#797 bug: Fix invalid allowed value for hubRoutingPreference
  infra-as-code/bicep/modules/vwanConnectivity/generateddocs/vwanConnectivity.bicep.md
  infra-as-code/bicep/modules/vwanConnectivity/samples/baseline.sample.bicep
  infra-as-code/bicep/modules/vwanConnectivity/vwanConnectivity.bicep
Labels: Area: Networking :globe_with_meridians:, Type: Bug :beetle:
