Repository Azure/ALZ-Bicep, pull requests merged in 2024-08, with the labels that each got.

#816 Adding RBAC constrained delegation parameters and guidance in the roleAssignment modules
  infra-as-code/bicep/modules/roleAssignments/README.md
  infra-as-code/bicep/modules/roleAssignments/generateddocs/roleAssignmentManagementGroup.bicep.md
  infra-as-code/bicep/modules/roleAssignments/generateddocs/roleAssignmentManagementGroupMany.bicep.md
  infra-as-code/bicep/modules/roleAssignments/generateddocs/roleAssignmentResourceGroup.bicep.md
  infra-as-code/bicep/modules/roleAssignments/generateddocs/roleAssignmentResourceGroupMany.bicep.md
  infra-as-code/bicep/modules/roleAssignments/generateddocs/roleAssignmentSubscription.bicep.md
  infra-as-code/bicep/modules/roleAssignments/generateddocs/roleAssignmentSubscriptionMany.bicep.md
  infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentManagementGroup.managedIdentity.parameters.all.json
  infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentManagementGroup.securityGroup.parameters.all.json
  infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentManagementGroup.servicePrincipal.parameters.all.json
  infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentManagementGroupMany.managedIdentity.parameters.all.json
  infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentManagementGroupMany.securityGroup.parameters.all.json
  infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentManagementGroupMany.servicePrincipal.parameters.all.json
  infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentResourceGroup.managedIdentity.parameters.all.json
  infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentResourceGroup.securityGroup.parameters.all.json
  infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentResourceGroup.servicePrincipal.parameters.all.json
  infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentResourceGroupMany.managedIdentity.parameters.all.json
  infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentResourceGroupMany.securityGroup.parameters.all.json
  infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentResourceGroupMany.servicePrincipal.parameters.all.json
  infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentSubscription.managedIdentity.parameters.all.json
  infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentSubscription.securityGroup.parameters.all.json
  infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentSubscription.servicePrincipal.parameters.all.json
  infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentSubscriptionMany.managedIdentity.parameters.all.json
  infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentSubscriptionMany.securityGroup.parameters.all.json
  infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentSubscriptionMany.servicePrincipal.parameters.all.json
  infra-as-code/bicep/modules/roleAssignments/roleAssignmentManagementGroup.bicep
  infra-as-code/bicep/modules/roleAssignments/roleAssignmentManagementGroupMany.bicep
  infra-as-code/bicep/modules/roleAssignments/roleAssignmentResourceGroup.bicep
  infra-as-code/bicep/modules/roleAssignments/roleAssignmentResourceGroupMany.bicep
  infra-as-code/bicep/modules/roleAssignments/roleAssignmentSubscription.bicep
  infra-as-code/bicep/modules/roleAssignments/roleAssignmentSubscriptionMany.bicep
Labels: Area: RBAC :passport_control:, Type: Documentation :page_facing_up:, Type: Enhancement :sparkles:

#827 Fix safe access linter warnings
  infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep
Labels: Type: Enhancement :sparkles:, Type: Hygiene :broom:

#826 Added newer linter-rules
  infra-as-code/bicep/bicepconfig.json
Labels: Type: Enhancement :sparkles:, Type: Hygiene :broom:

#829 Updated api version for automation account
  infra-as-code/bicep/modules/logging/logging.bicep
Labels: Area: Logging & Automation :camera:
