Repository Azure/ALZ-Bicep, pull requests merged in 2024-11, with the labels that each got.

#891 fix: Private DNS Zones Bug (#695)
  accelerator/.config/ALZ-Powershell-Auto.config.json
  accelerator/.config/ALZ-Powershell.config.json
  docs/wiki/CustomerUsage.md
  infra-as-code/bicep/modules/hubNetworking/README.md
  infra-as-code/bicep/modules/hubNetworking/generateddocs/hubNetworking-multiRegion.bicep.md
  infra-as-code/bicep/modules/hubNetworking/generateddocs/hubNetworking.bicep.md
  infra-as-code/bicep/modules/hubNetworking/hubNetworking-multiRegion.bicep
  infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep
  infra-as-code/bicep/modules/hubNetworking/parameters/hubNetworking.parameters.all.json
  infra-as-code/bicep/modules/hubNetworking/parameters/hubNetworking.parameters.az.all.json
  infra-as-code/bicep/modules/hubNetworking/parameters/hubNetworking.parameters.az.multiRegion.all.json
  infra-as-code/bicep/modules/privateDnsZones/README.md
  infra-as-code/bicep/modules/privateDnsZones/bicepconfig.json
  infra-as-code/bicep/modules/privateDnsZones/generateddocs/privateDnsZones.bicep.md
  infra-as-code/bicep/modules/privateDnsZones/media/bicepVisualizer.png
  infra-as-code/bicep/modules/privateDnsZones/media/exampleDeploymentOutput.png
  infra-as-code/bicep/modules/privateDnsZones/parameters/mc-privateDnsZones.parameters.all.json
  infra-as-code/bicep/modules/privateDnsZones/parameters/mc-privateDnsZones.parameters.min.json
  infra-as-code/bicep/modules/privateDnsZones/parameters/privateDnsZones.parameters.all.json
  infra-as-code/bicep/modules/privateDnsZones/parameters/privateDnsZones.parameters.min.json
  infra-as-code/bicep/modules/privateDnsZones/privateDnsZones.bicep
  infra-as-code/bicep/modules/privateDnsZones/samples/baseline.sample.bicep
  infra-as-code/bicep/modules/privateDnsZones/samples/generateddocs/baseline.sample.bicep.md
  infra-as-code/bicep/modules/privateDnsZones/samples/generateddocs/minimum.sample.bicep.md
  infra-as-code/bicep/modules/privateDnsZones/samples/minimum.sample.bicep
  infra-as-code/bicep/modules/vwanConnectivity/generateddocs/vwanConnectivity.bicep.md
  infra-as-code/bicep/modules/vwanConnectivity/parameters/vwanConnectivity.parameters.all.json
  infra-as-code/bicep/modules/vwanConnectivity/parameters/vwanConnectivity.parameters.az.all.json
  infra-as-code/bicep/modules/vwanConnectivity/parameters/vwanConnectivity.parameters.az.multiRegion.all.json
  infra-as-code/bicep/modules/vwanConnectivity/samples/baseline.sample.bicep
  infra-as-code/bicep/modules/vwanConnectivity/samples/minimum.sample.bicep
  infra-as-code/bicep/modules/vwanConnectivity/vwanConnectivity.bicep
  tests/pipelines/base-unit-validate.yml
  tests/pipelines/mc-base-unit-validate.yml
Labels: Area: Networking :globe_with_meridians:, Type: Bug :beetle:

#898 chore: Adjust permission scopes
  .github/workflows/bicep-build-to-validate.yml
  .github/workflows/code-review.yml
  .github/workflows/psdocs-mdtogit.yml
  .github/workflows/release.yml
  .github/workflows/scheduled-bicep-build.yml
  .github/workflows/scorecard.yml
Labels: Type: Hygiene :broom:

#908 docs: Update known issues wiki
  docs/wiki/KnownIssues.md
Labels: Type: Documentation :page_facing_up:

#910 docs: Update known issues with Azure PowerShell v13.0.0
  docs/wiki/KnownIssues.md
Labels: Type: Documentation :page_facing_up:

#915 feat: updates to fix Region name now being appended to azFw policy name #914
  infra-as-code/bicep/modules/vwanConnectivity/generateddocs/vwanConnectivity.bicep.md
  infra-as-code/bicep/modules/vwanConnectivity/parameters/mc-vwanConnectivity.parameters.all.json
  infra-as-code/bicep/modules/vwanConnectivity/parameters/vwanConnectivity.parameters.all.json
  infra-as-code/bicep/modules/vwanConnectivity/parameters/vwanConnectivity.parameters.az.multiRegion.all.json
  infra-as-code/bicep/modules/vwanConnectivity/vwanConnectivity.bicep
Labels: Area: Networking :globe_with_meridians:, Type: Feature Request :heavy_plus_sign:
